name: Build and push image to Dockerhub

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
        with:
          commit: "${{ github.event.workflow_run.head_sha }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.commit.outputs.short }}